// <auto-generated />
namespace YangKai.BlogEngine.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddQrCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddQrCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201210111246442_AddQrCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
