// <auto-generated />
namespace YangKai.BlogEngine.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddGallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGallery));
        
        string IMigrationMetadata.Id
        {
            get { return "201310180858151_AddGallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
